@baseUrl = http://localhost:3333/api
@authToken = {{authenticate.response.body.access_token}}
@machineId = {{create_machine.response.body.machineId}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "firstName": "Rhaniel",
  "lastName": "Xavier",
  "email": "rhaniel@mag.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "rhaniel@mag.com.br",
  "password": "123456"
}

###

# @name create_machine
POST {{baseUrl}}/machines
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Machine 4",
  "type": "PUMP"
}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_machine
PUT {{baseUrl}}/machines/6ed473f0-077d-4e43-b788-be67fe438bb3
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Machine 2"
}

###

# @name delete_machine
DELETE {{baseUrl}}/machines/6ed473f0-077d-4e43-b788-be67fe438bb3
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_sensor
POST {{baseUrl}}/sensors
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Sensor 2",
  "model": "HF"
}

###

# @name create_monitoring_points
POST {{baseUrl}}/machines/5ec4373d-bf38-416d-854e-48a03a5e95f0/monitoring-points
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "MP"  
}

###

# @name link_sensor_to_monitoring_point
PATCH {{baseUrl}}/machines/monitoring-points/ab4a5e23-82a5-4aeb-bc04-f57e011e0e6a
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "sensorId": "211a25af-f407-4d74-869a-26754be52a15"
}