@baseUrl = http://localhost:3333/api
@authToken = {{authenticate.response.body.access_token}}
@machineId = {{create_machine.response.body.machineId}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "firstName": "Rhaniel",
  "lastName": "Xavier",
  "email": "rhaniel@mag.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "rhaniel@mag.com.br",
  "password": "123456"
}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_machine
POST {{baseUrl}}/machines
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Machine 3",
  "type": "PUMP"
}

###

# @name fetch_machines
GET {{baseUrl}}/machines
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_machine
PUT {{baseUrl}}/machines/6ed473f0-077d-4e43-b788-be67fe438bb3
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Machine 2"
}

###

# @name delete_machine
DELETE {{baseUrl}}/machines/6ed473f0-077d-4e43-b788-be67fe438bb3
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_monitoring_points
POST {{baseUrl}}/machines/6afdde53-c655-44a1-bf80-7a465e7b4275/monitoring-points
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "MP 3"  
}


###

# @name create_sensor
POST {{baseUrl}}/sensors
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Sensor 3",
  "model": "HF",
  "monitoringPointId": "1d766f26-4d4e-4008-860a-fd60e963cfbf"
}

###

# @name fetch_sensors
GET {{baseUrl}}/sensors
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name link_sensor_to_monitoring_point
PATCH {{baseUrl}}/machines/monitoring-points/586b1eae-1351-4921-aa7c-611eda66cbc4
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "sensorId": "e232a0c7-17f5-4f4a-aaf2-e2b152fb21f2"
}