version: '3.8'
services:
  postgres:
    container_name: dynamo-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB=value: dynamo-db
    volumes:
      - ./data/pg:/data/postgres
